WARNING: linker: _imaging.cpython-37m.so: unused DT entry: type 0x6ffffef5 arg 0xbe0
WARNING: linker: _multidict.cpython-37m.so: unused DT entry: type 0x6ffffef5 arg 0x5d8
WARNING: linker: _istr.cpython-37m.so: unused DT entry: type 0x6ffffef5 arg 0x1c4
WARNING: linker: _quoting.cpython-37m.so: unused DT entry: type 0x6ffffef5 arg 0x554
WARNING: linker: _helpers.cpython-37m.so: unused DT entry: type 0x6ffffef5 arg 0x448
WARNING: linker: _http_writer.cpython-37m.so: unused DT entry: type 0x6ffffef5 arg 0x430
WARNING: linker: _http_parser.cpython-37m.so: unused DT entry: type 0x6ffffef5 arg 0x5fc
WARNING: linker: _websocket.cpython-37m.so: unused DT entry: type 0x6ffffef5 arg 0x378
WARNING: linker: _frozenlist.cpython-37m.so: unused DT entry: type 0x6ffffef5 arg 0x46c
2019-06-02 18:54:49,680 - userbot - INFO - Modules to load: ['admin', 'afk', 'chat', 'dogbin', 'download', 'evaluators', 'filter', 'hash', 'help', 'kang', 'memes', 'misc', 'mute_chat', 'notes', 'pmpermit', 'purge', 'qrcode', 'scrapers', 'screencapture', 'sed', 'spotify', 'system_stats', 'time', 'updater', 'userdata', 'weather', 'welcomes', 'whois', 'www']
2019-06-02 18:54:49,685 - telethon.network.mtprotosender - INFO - Connecting to 91.108.56.120:443/TcpFull...
2019-06-02 18:54:49,754 - telethon.network.mtprotosender - INFO - Connection to 91.108.56.120:443/TcpFull complete!
WARNING: linker: _pybase64.cpython-37m.so: unused DT entry: type 0x6ffffef5 arg 0x2ac
WARNING: linker: _imaging.cpython-37m.so: unused DT entry: type 0x6ffffef5 arg 0xbe0
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data/data/com.termux/files/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/data/com.termux/files/home/Telegram-UserBot/userbot/__main__.py", line 34, in <module>
    imported_module = import_module("userbot.modules." + module_name)
  File "/data/data/com.termux/files/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data/data/com.termux/files/home/Telegram-UserBot/userbot/modules/kang.py", line 13, in <module>
    from PIL import Image
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/PIL/Image.py", line 93, in <module>
    from . import _imaging as core
ImportError: dlopen failed: cannot locate symbol "modf" referenced by "_imaging.cpython-37m.so"...
